[package]
name = "token_contract"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", directory = "noir-projects/aztec-nr/aztec",  tag="v1.2.0" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages", directory = "noir-projects/aztec-nr/uint-note",  tag="v1.2.0" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages", directory = "noir-projects/aztec-nr/compressed-string",  tag="v1.2.0" }
